PizzaStar/Controllers/ShopCartController.cs
using Microsoft.AspNetCore.Mvc;
using PizzaStar.Interfaces;

namespace PizzaStar.Controllers;

public class ShopCartController : Controller
{
    private readonly IProduct _products;
    private readonly CartRepository _cartRepository;
 
    public ShopCartController(IProduct products, CartRepository cartRepository)
    {
        _products = products;
        _cartRepository = cartRepository;
    }
 
    [Route("/cart")]
    [HttpGet]
    public async Task<IActionResult> Index()
    {
        //Что бы не была установлена активной главная страница.
        ViewBag.CategoryId = double.NaN;
        var products = await _cartRepository.GetShopCartItemsAsync();
        _cartRepository.ShopCartItems = products.ToList();
        return View(products);
    }
 
    [HttpPost]
    [AutoValidateAntiforgeryToken]
    public async Task<IActionResult> AddToCart(int productId, string? returnUrl, int quantity = 1, bool isModal = true)
    {
        var product = await _products.GetProductAsync(productId);
        if (product != null)
        {
            await _cartRepository.AddToCartAsync(product, quantity);
            if (isModal)
            {
                return PartialView("_ConfirmModal", (product.Name, quantity));
            }
        }
        if (returnUrl != null)
        {
            return Redirect(returnUrl);
        }
        return RedirectToAction(nameof(Index));
    }
    [HttpPost]
    [AutoValidateAntiforgeryToken]
    public async Task<IActionResult> IncrementQuantity(int shopCartItemId)
    {
        var currentShopCartItem = await _cartRepository.GetShopCartItemAsync(shopCartItemId);
        if (currentShopCartItem != null)
        {
            currentShopCartItem.Count += 1;
            await _cartRepository.UpdateFromCartAsync(currentShopCartItem);
        }
        return RedirectToAction(nameof(Index));
    }
    [HttpPost]
    [AutoValidateAntiforgeryToken]
    public async Task<IActionResult> DecrementQuantity(int shopCartItemId)
    {
        var currentShopCartItem = await _cartRepository.GetShopCartItemAsync(shopCartItemId);
        if (currentShopCartItem.Count > 1)
        {
            if (currentShopCartItem != null)
            {
                currentShopCartItem.Count -= 1;
                await _cartRepository.UpdateFromCartAsync(currentShopCartItem);
            }
        }
        return RedirectToAction(nameof(Index));
    }
    [HttpPost]
    [AutoValidateAntiforgeryToken]
    public async Task<IActionResult> RemoveFromCart(int shopCartItemId)
    {
        var currentShopCartItem = await _cartRepository.GetShopCartItemAsync(shopCartItemId);
        if (currentShopCartItem != null)
        {
            await _cartRepository.RemoveFromCartAsync(currentShopCartItem);
        }
        return RedirectToAction(nameof(Index));
    }
}

PizzaStar/Views/Shared/_ConfirmModal.cshtml
@model (string Name, int Quantity)
 
<div class="modal" id="confirmProductModal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Успешно добавлено!</h5>
            </div>
            <div class="modal-body">
                <p>@Model.Name, в количестве @Model.Quantity добавлено в корзину.</p>
            </div>
            <div class="modal-footer">
                <a asp-action="Index" asp-controller="ShopCart" class="btn btn-secondary">В корзину</a>
                <button id="btn-No" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
            </div>
        </div>
    </div>
</div>
 
 
<script>
    $(document).ready(function () {
        //При открытии формы, указываем всплывающее окно
        $("#confirmProductModal").modal('show');
        // Close modal on button click
        $(".btn").click(function () {
            $("#confirmProductModal").modal('hide');
        });
        //Событие закрытие формы (закрыть форму могут нажав в любом месте
        // за формой или по кнопку, поэтому обрабатываем в событии закрытия)
        $("#confirmProductModal").on("hidden.bs.modal", function () {
            //Обращаемся к корзине и обновляем количество товара
            var shopCart = document.getElementById("cartProductNumber");
            console.log(shopCart);
            const quantity = parseInt(shopCart.innerText);
            console.log(quantity);
            shopCart.innerText = (quantity + 1);
        });
    });
</script>

PizzaStar/Views/Shared/_ItemsFilter.cshtml
<aside id="column-left" class="col-sm-3">
    <div class="panel panel-default filter">
        <div class="box-content">
            <div id="filter">
                <h3 class="toggle relative">Фильтрация</h3>
                <div class="filter_box">
                    <div class="list-group">
                        <div class="list-group-items">
                            <a class="list-group-item">Стоимость</a>
                            <div class="list-group-item">
                                <div id="filter-group2">
                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox" value="1" class="form-check-input">
                                            ₴60 - ₴120
                                        </label>
                                    </div>
                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox" value="2" class="form-check-input">
                                            ₴121 - ₴150
                                        </label>
                                    </div>
                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox" value="3" class="form-check-input">
                                            ₴151 - ₴220
                                        </label>
                                    </div>
                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox" value="4" class="form-check-input">
                                            ₴221 - ₴350
                                        </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="list-group-items">
                            <a class="list-group-item">Бренд</a>
                            <div class="list-group-item">
                                <div id="filter-group3">
                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox" name="filter[]" value="5" class="form-check-input">
                                            Calpone
                                        </label>
                                    </div>
                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox" name="filter[]" value="6" class="form-check-input">
                                            Silpo
                                        </label>
                                    </div>
                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox" name="filter[]" value="7" class="form-check-input">
                                            PizzaDay
                                        </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="panel-footer text-right">
                        <button class="btn btn-primary" type="button">Фильтр</button>
                    </div>                
                </div>
            </div>
        </div>
    </div>
    <div class="swiper-viewport">
        <div id="banner0" class="swiper-container swiper-container-horizontal swiper-container-fade">
            <div class="swiper-wrapper">
                <div class="swiper-slide swiper-slide-active">
                    <a><img src="assets/images/banners/category_banner2.jpg" class="img-responsive"></a>
                </div>
            </div>
        </div>
    </div>
</aside>

PizzaStar/Views/Shared/_Modal.cshtml
@model string


<div class="modal" id="confirmModal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Подтвердите действие</h5>
            </div>
            <div class="modal-body">
                <p>@Model</p>
            </div>
            <div class="modal-footer">
                @*Обязательно прописываем ID*@
                <button id="btn-Yes" class="btn btn-secondary">Удалить</button>
                <button id="btn-No" class="btn btn-secondary" data-dismiss="modal">Отмена</button>
            </div>
        </div>
    </div>
</div>

PizzaStar/Views/Shared/_Pages.cshtml
<form method="get" class="form-inline m-3" id="pageform">

    <input type="hidden" name="categoryId" value="@ViewBag.CategoryId" />
    
    <button name="options.CurrentPage" value="@(Model.CurrentPage - 1)"
            class="btn btn-primary @(!Model.HasPreviousPage ? "disabled" : "")" type="submit">
        Назад
    </button>

    @for (int i = 1; i <= 3 && i <= Model.TotalPages; i++)
    {
        <button name="options.CurrentPage" value="@i" type="submit"
                class="btn btn-outline-primary @(Model.CurrentPage == i ? "active" : "")">
            @i
        </button>
    }
    @if (Model.CurrentPage > 3 && Model.TotalPages - Model.CurrentPage >= 3)
    {
        @:...
        <button class="btn btn-outline-primary active">@Model.CurrentPage</button>
    }
    @if (Model.TotalPages > 3)
    {
        @:...
        @for (int i = Math.Max(4, Model.TotalPages - 2); i <= Model.TotalPages; i++)
        {
            <button name="options.CurrentPage" value="@i" type="submit"
                    class="btn btn-outline-primary @(Model.CurrentPage == i ? "active" : "")">
                @i
            </button>
        }
    }
    <button name="options.CurrentPage" value="@(Model.CurrentPage + 1)" type="submit"
            class="btn btn-primary @(!Model.HasNextPage ? "disabled" : "")">
        Вперед
    </button>


    <select name="options.PageSize" class="my-form-control">
        @foreach (int val in new int[] { 2, 25, 50, 100 })
        {
            <option value="@val" selected="@(Model.PageSize == val)">@val</option>
        }
    </select>
    <input type="hidden" name="options.CurrentPage" value="1"/>
    <button type="submit" class="btn btn-outline-primary">Изменить размер страницы</button>
</form>

PizzaStar/Views/Shared/_ScriptsPartial.cshtml
<script src="~/assets/js/vendors/jquery-2.1.1.min.js" type="text/javascript"></script>
<script type="text/javascript" src="~/assets/js/bootstrap.min.js"></script>
<script type="text/javascript" src="~/assets/js/owl.carousel.min.js"></script>
<script src="~/assets/js/themability_megamenu.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/wow/1.1.2/wow.min.js" type="text/javascript"></script>
<script type="text/javascript">new WOW().init();</script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css" rel="stylesheet" />
<script type="text/javascript" src="~/assets/js/theme.js"></script>

PizzaStar/Views/Shared/_SearchOptions.cshtml
<select form="pageform" name="options.searchpropertyname" class="form-control">
    @foreach (string s in ViewBag.searches as string[])
    {
        <option value="@s" selected="@(Model.Options.SearchPropertyName == s)">
            @(
                s switch
                {
                    "Email" => "Емейл",
                    "PhoneNumber" => "Телефон",
                    "Name" => "Название",
                    "Description" => "Описание",
                    "Brand" => "Бренд",
                    "Category.Name" => "Категория",
                    _ => s
                }
                )
        </option>
    }
</select>


<input form="pageform" name="options.searchterm" value="@Model.Options.SearchTerm" placeholder="Поиск..." class="form-control input-lg ui-autocomplete-input" />
<span class="btn-search input-group-btn">
    <button form="pageform" type="submit" class="btn btn-default btn-lg"><i class="fa fa-search"></i></button>
</span>

PizzaStar/Views/Shared/_SortOptions.cshtml
<div class="sort-cat">
    <div class="text-category-sort">
        <label class="input-group-addon" for="input-sort">Сортировать по:</label>
    </div>
    <div class="select-cat-sort">
        <select name="options.OrderPropertyName" class="form-control" form="pageform">
            @foreach(string s in ViewBag.sorts as string[])
            {
                string value = s.IndexOf('.') == -1 ? s : s.Substring(s.IndexOf('.') + 1);
                <option value="@s" selected="@(Model.Options.OrderPropertyName == s)">
                    @(
                    s switch
                    {
                        "Price" => "Стоимость",
                        "Calories" => "Калорийность",
                        "Weight" => "Вес",
                        "Name" => "Название",
                        "Description" => "Описание",
                        "Brand" => "Бренд",
                        "Category.Name" => "Категория",
                        _ => value
                    }
                    )
                </option>
            }
        </select>
    </div>
</div>
<div class="limit-cat">
    <div class="text-category-limit">
        <label class="input-group-addon" for="input-limit">По убыванию:</label>
    </div>
    <div class="text-category-limit">
        <input type="checkbox" form="pageform" name="Options.DescendingOrder" id="Options.DescendingOrder" class="form-check-input"
               value="true" checked="@Model.Options.DescendingOrder" style="margin: 8px 0 0"/>&nbsp&nbsp;
    </div>
    <div class="text-category-limit">
        <button form="pageform" class="btn btn-success" type="submit" style="background: var(--secondary-hover-color);">
            Сортировать
        </button>
    </div>
</div>

PizzaStar/Views/Shared/_StylesPartial.cshtml
<link rel="icon" type="image/png" href="~/assets/images/favicon.png">
<link rel="stylesheet" href="~/assets/css/bootstrap.min.css">
<link rel="stylesheet" href="~/assets/css/owl.carousel.css" type="text/css" media="all" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" />
<link rel="stylesheet" href="~/assets/fonts/themability-font.css" type="text/css" media="all">
<link rel="stylesheet" href="~/assets/css/style.css" type="text/css" media="all" />
<link href="https://fonts.googleapis.com/css2?family=Lobster&family=Poppins:wght@300;400;500;600;700;800;900&display=swap" rel="stylesheet">
<link rel="stylesheet" href="~/assets/css/themability_megamenu.css">