PizzaStar/Controllers/DishController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using PizzaStar.Interfaces;
using PizzaStar.Models;
using PizzaStar.Models.Pages;
using PizzaStar.ViewModels;

namespace PizzaStar.Controllers
{
    [Authorize(Roles = "Admin,Editor")]
    public class DishController : Controller
    {
        private readonly IProduct _products;
        private readonly ICategory _categories;
        private readonly IWebHostEnvironment _appEnvironment;

        public DishController(IProduct products, IWebHostEnvironment appEnvironment, ICategory categories)
        {
            _products = products;
            _appEnvironment = appEnvironment;
            _categories = categories;
        }

        [Route("/panel/dishes")]
        [HttpGet]
        public IActionResult Dishes(QueryOptions options)
        {
            return View(_products.GetAllProducts(options));
        }

        [Route("/panel/delete-product")]
        [HttpDelete]
        public async Task<IActionResult> DeleteProduct(int productId)
        {
            var currentProduct = await _products.GetProductAsync(productId);
            if (currentProduct != null)
            {
                if (currentProduct.Image != null)
                {
                    if (System.IO.File.Exists(_appEnvironment.WebRootPath + currentProduct.Image))
                    {
                        System.IO.File.Delete(_appEnvironment.WebRootPath + currentProduct.Image);
                    }
                }
                await _products.DeleteProductAsync(currentProduct);
            }
            return Ok();
        }

        [Route("/panel/create-product")]
        [HttpGet]
        public async Task<IActionResult> CreateProduct()
        {
            var categories = await _categories.GetAllCategoriesAsync();
            return View(new ProductViewModel
            {
                AllCategories = new SelectList(categories, "Id", "Name")
            });
        }


        [Route("/panel/create-product")]
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> CreateProduct(ProductViewModel productViewModel)
        {
            if (ModelState.IsValid)
            {
                productViewModel.DateOfPublication = DateTime.Now;
                var currentProduct = new Product
                {
                    Name = productViewModel.Name!,
                    Description = productViewModel.Description!,
                    Type = productViewModel.Type,
                    Brand = productViewModel.Brand,
                    Calories = productViewModel.Calories,
                    Price = productViewModel.Price,
                    Weight = productViewModel.Weight,
                    CategoryId = productViewModel.CategoryId,
                    DateOfPublication = DateTime.Now
                };
                if (productViewModel.File != null)
                {
                    string fileName = productViewModel.File.FileName;
                    if (fileName.Contains("\\"))
                    {
                        fileName = fileName.Substring(fileName.LastIndexOf('\\') + 1);
                    }
                    string filePath = "/productFiles/" + Guid.NewGuid().ToString() + fileName;
                    currentProduct.Image = filePath;


                    using (var fileStream = new FileStream(_appEnvironment.WebRootPath + filePath, FileMode.Create))
                    {
                        await productViewModel.File.CopyToAsync(fileStream);
                    }
                }
                await _products.AddProductAsync(currentProduct);
                return RedirectToAction(nameof(Dishes));
            }
            return View(productViewModel);
        }


        [Route("/panel/edit-product")]
        [HttpGet]
        public async Task<IActionResult> EditProduct(int productId)
        {
            var currentProduct = await _products.GetProductAsync(productId);
            if (currentProduct != null)
            {
                var categories = await _categories.GetAllCategoriesAsync();
                ProductViewModel productViewModel = new ProductViewModel
                {
                    Id = currentProduct.Id,
                    Name = currentProduct.Name,
                    Image = currentProduct.Image,
                    Description = currentProduct.Description,
                    Brand = currentProduct.Brand,
                    Calories = currentProduct.Calories,
                    Price = currentProduct.Price,
                    Type = currentProduct.Type,
                    Weight = currentProduct.Weight,
                    CategoryId = currentProduct.CategoryId,
                    AllCategories = new SelectList(categories, "Id", "Name")
                };
                return View(productViewModel);
            }
            return NotFound();
        }


        [Route("/panel/edit-product")]
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> EditProduct(ProductViewModel productViewModel)
        {
            if (ModelState.IsValid)
            {
                var selectedProduct = await _products.GetProductAsync(productViewModel.Id ?? 0);
                if (selectedProduct == null)
                {
                    return NotFound();
                }
                var currentProduct = new Product
                {
                    Id = productViewModel.Id ?? 0,
                    Name = productViewModel.Name!,
                    Description = productViewModel.Description!,
                    Image = selectedProduct.Image,
                    Brand = productViewModel.Brand,
                    Calories = productViewModel.Calories,
                    Price = productViewModel.Price,
                    Type = productViewModel.Type,
                    Weight = productViewModel.Weight,
                    CategoryId = productViewModel.CategoryId
                };
                if (productViewModel.File != null)
                {
                    if (selectedProduct.Image != null)
                    {
                        if (System.IO.File.Exists(_appEnvironment.WebRootPath + selectedProduct.Image))
                        {
                            System.IO.File.Delete(_appEnvironment.WebRootPath + selectedProduct.Image);
                        }
                    }
                    string fileName = productViewModel.File.FileName;
                    if (fileName.Contains("\\"))
                    {
                        fileName = fileName.Substring(fileName.LastIndexOf('\\') + 1);
                    }
                    string filePath = "/productFiles/" + Guid.NewGuid().ToString() + fileName;
                    currentProduct.Image = filePath;


                    using (var fileStream = new FileStream(_appEnvironment.WebRootPath + filePath, FileMode.Create))
                    {
                        await productViewModel.File.CopyToAsync(fileStream);
                    }
                }
                await _products.EditProductAsync(currentProduct);
                return RedirectToAction(nameof(Dishes));
            }
            return View(productViewModel);
        }



    }

}

PizzaStar/Controllers/PanelController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PizzaStar.Data;
using PizzaStar.Models;
using PizzaStar.Models.Pages;
using PizzaStar.ViewModels;

namespace PizzaStar.Controllers
{
    [Authorize(Roles = "Admin,Editor")]
    public class PanelController : Controller
    {

        private readonly UserManager<User> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly ApplicationContext _context;
        public PanelController(UserManager<User> userManager, RoleManager<IdentityRole> roleManager, ApplicationContext context)
        {
            _userManager = userManager;
            _roleManager = roleManager;
            _context = context;
        }


        [Route("/panel")]
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }


        [Authorize(Roles = "Admin")]
        [Route("/panel/users")]
        [HttpGet]
        public IActionResult Users(QueryOptions options)
        {
            var pagedList = new PagedList<User>(_userManager.Users, options);
            return View(pagedList);
        }


        [Authorize(Roles = "Admin")]
        [Route("/panel/create-update-user")]
        [HttpGet]
        public async Task<IActionResult> CreateOrUpdateUser(string? userId)
        {
            if (userId is null)
            {
                return View(new CreateOrUpdateUserViewModel());
            }
            else
            {
                User user = await _userManager.FindByIdAsync(userId);
                if (user == null)
                {
                    return NotFound();
                }
                CreateOrUpdateUserViewModel model = new CreateOrUpdateUserViewModel
                {
                    Id = user.Id,
                    Email = user.Email,
                    Phone = user.PhoneNumber,
                    Year = user.Year,
                };
                return View(model);
            }
        }


        [Authorize(Roles = "Admin")]
        [Route("/panel/create-update-user")]
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> CreateOrUpdateUser(CreateOrUpdateUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (model.Id is null)
                {
                    var userCheck = await _userManager.FindByEmailAsync(model.Email);
                    if (userCheck != null)
                    {
                        ModelState.AddModelError("Email", "Такой емейл адрес уже занят.");
                        return View(model);
                    }
                    User user = new User { Email = model.Email, UserName = model.Email, PhoneNumber = model.Phone, Year = model.Year };
                    var result = await _userManager.CreateAsync(user, model.Password);
                    if (result.Succeeded)
                    {
                        result = await _userManager.AddToRoleAsync(user, "Client");
                        return RedirectToAction(nameof(Users));
                    }
                    else
                    {
                        foreach (var error in result.Errors)
                        {
                            ModelState.AddModelError(string.Empty, error.Description);
                        }
                    }
                }
                else
                {
                    User user = await _userManager.FindByIdAsync(model.Id);
                    if (user != null)
                    {
                        if (!user.Email.Equals(model.Email))
                        {
                            var userCheck = await _userManager.FindByEmailAsync(model.Email);
                            if (userCheck != null)
                            {
                                ModelState.AddModelError("Email", "Такой емейл адрес уже занят.");
                                return View(model);
                            }
                        }
                        user.Email = model.Email;
                        user.UserName = model.Email;
                        user.Year = model.Year;
                        user.PhoneNumber = model.Phone;
                        var result = await _userManager.UpdateAsync(user);
                        if (result.Succeeded)
                        {
                            return RedirectToAction(nameof(Users));
                        }
                        else
                        {
                            foreach (var error in result.Errors)
                            {
                                ModelState.AddModelError(string.Empty, error.Description);
                            }
                        }
                    }
                }
            }
            return View(model);
        }

        [Authorize(Roles = "Admin")]
        [Route("/panel/delete-user")]
        [HttpDelete]
        public async Task<ActionResult> DeleteUser(string userId)
        {
            User user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                IdentityResult result = await _userManager.DeleteAsync(user);
            }
            return Ok();
        }


        [Authorize(Roles = "Admin")]
        [Route("/panel/edit-role")]
        [HttpGet]
        public async Task<IActionResult> EditRole(string userId)
        {
            // получаем пользователя
            User user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                // получаем список ролей пользователя
                var userRoles = await _userManager.GetRolesAsync(user);
                var allRoles = _roleManager.Roles.ToList();
                ChangeRoleViewModel model = new ChangeRoleViewModel
                {
                    UserId = user.Id,
                    UserEmail = user.Email,
                    UserRoles = userRoles,
                    AllRoles = allRoles
                };
                return View(model);
            }
            return NotFound();
        }


        [Authorize(Roles = "Admin")]
        [Route("/panel/edit-role")]
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> EditRole(string userId, List<string> roles)
        {
            // получаем пользователя
            User user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                // получем список ролей пользователя
                var userRoles = await _userManager.GetRolesAsync(user);


                // получаем список ролей, которые были добавлены
                var addedRoles = roles.Except(userRoles);
                // получаем роли, которые были удалены
                var removedRoles = userRoles.Except(roles);


                await _userManager.AddToRolesAsync(user, addedRoles);
                await _userManager.RemoveFromRolesAsync(user, removedRoles);


                return RedirectToAction(nameof(Users));
            }
            return NotFound();
        }

        [Authorize(Roles = "Admin")]
        [Route("/panel/statistics")]
        [HttpGet]
        public IActionResult Statistics()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        [Route("/panel/set-contact")] 
        [HttpGet]
        public IActionResult Contact(QueryOptions options)
        {
            var pagedList = new PagedList<Contact>(_context.Contacts, options);
            return View(pagedList);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> CreateContact(string email)
        {
            if (ModelState.IsValid)
            {
                await _context.Contacts.AddAsync(new Contact{Email = email});
                await _context.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Contact));
        }

        [Authorize(Roles = "Admin")]
        [HttpDelete]
        [Route("/panel/delete-contact")]
        public IActionResult DeleteContact(string id)
        {
            if (!int.TryParse(id, out int contactId))
            {
                return BadRequest("Некорректный ID");
            }

            var email = _context.Contacts.Find(contactId);
            if (email == null)
            {
                return NotFound("Email не найден");
            }

            _context.Contacts.Remove(email);
            _context.SaveChanges();

            return Ok(new { message = "Email удалён успешно" });
        }
    }
}

PizzaStar/Controllers/RoleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace PizzaStar.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;

        public RoleController(RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
        }

        public IActionResult Index()
        {
            var roles = _roleManager.Roles;
            return View("~/Views/Panel/RoleManager.cshtml", roles);
        }

        [HttpPost]
        public async Task<IActionResult> Create(string roleName)
        {
            if (string.IsNullOrWhiteSpace(roleName))
                return RedirectToAction("Index");

            var roleExists = await _roleManager.RoleExistsAsync(roleName);
            if (!roleExists)
            {
                await _roleManager.CreateAsync(new IdentityRole(roleName));
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Edit(string roleId, string newRoleName)
        {
            var role = await _roleManager.FindByIdAsync(roleId);
            if (role != null)
            {
                role.Name = newRoleName;
                await _roleManager.UpdateAsync(role);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string roleId)
        {
            var role = await _roleManager.FindByIdAsync(roleId);
            if (role != null)
            {
                await _roleManager.DeleteAsync(role);
            }
            return RedirectToAction("Index");
        }
    }
}

PizzaStar/Views/Panel/Contact.cshtml
@{
    Layout = "_PanelLayout.cshtml";
    ViewData["Title"] = "Пользователи";
}
@model IEnumerable<Contact>

<div class="breadcrumb-main">
    <div class="breadcrumb-container clearfix">
        <h1 class="page-title">Панель управления</h1>
        <ul class="breadcrumb">
            <li><a asp-action="Index" asp-controller="Panel">Главная</a></li>
            <li><a asp-action="Contact" asp-controller="Panel">Контактная информация</a></li>
        </ul>
    </div>
</div>


<div class="row g-4 py-5 row-cols-1">

    <form method="post" asp-action="CreateContact" asp-controller="Panel" class="row">
        <input type="email" name="Email" class="form-control mb-3" placeholder="your email" required>
        <button type="submit" class="btn btn-primary">Добавить новый контактный адрес эл. почты</button>
    </form>

    <div class="input-group themability-search">
        @{
            ViewBag.searches = new string[] { "Email" };
        }
        @await Html.PartialAsync("_SearchOptions", Model)
    </div>


    <div class="p-5 mb-4 bg-light rounded-3 ovx table-responsive">
        <table class="table">
            <tr><th>Email</th><th></th><th>
            @foreach (var email in Model)
            {
                @*Обязательно прописываем данный атрибут
            С помощью него мы удалим данную строку,
            используя JavaScript*@
                <tr data-rowid="@email.Id">
                    <td>@email.Email</td>
                    <td>
                        @*Обязательно прописываем onClick и метод, который будет обрабатывать клик*@
                        <button onclick="deleteEmail('@email.Id')" class="btn btn-sm btn-danger">Удалить</button>
                    </td>
                </tr>
            }
        </table>


        <div class="text-center">
            @await Html.PartialAsync("_Pages", Model)
        </div>


        @await Html.PartialAsync("_Modal", "Удалить выбранный email?")


        @section Scripts {
            <script>
                async function deleteEmail(emailId) {


                    const btnYes = document.getElementById('btn-Yes');
                    const btnNo = document.getElementById('btn-No');


                    $('#confirmModal').modal('show');


                    //Если нажали да, удаляем
                    btnYes.onclick = () => {
                        const deleteItem = fetch(`/panel/delete-contact/?id=${emailId}`, { method: 'DELETE' })
                            .then(response => {
                                if (!response.ok) {
                                    throw new Error('Network response was not ok');
                                }
                                //Удаляем строку
                                document.querySelector("tr[data-rowid='" + emailId + "']").remove();
                                //Закрываем модальное окно
                                $('#confirmModal').modal('hide');
                            })
                            .catch(error => {
                                console.error('There was a problem with the fetch operation:', error);
                                // Обработка ошибки удаления
                            });
                    }
                    //Если нажали нет, скрываем
                    btnNo.onclick = () => {
                        $('#confirmModal').modal('hide');
                    }
                }
            </script>
        }


    </div>
</div>

PizzaStar/Views/Panel/CreateOrUpdateUser.cshtml
@{
    Layout = "_PanelLayout.cshtml";
    ViewData["Title"] = Model.Id is null ? "Добавление пользователя" : "Редактирование пользователя";
}


@model CreateOrUpdateUserViewModel


<div class="row justify-content-center">
    <div class="col-sm-12">
        <div class="well mt-5">
            <h3>@(Model.Id is null ? "Добавление пользователя" : "Редактирование пользователя")</h3>
            <form method="post" asp-controller="Panel" asp-action="CreateOrUpdateUser">
                <div asp-validation-summary="ModelOnly"></div>


                @if (Model.Id is not null)
                {
                    <input asp-for="Id" type="hidden" />
                }


                <div class="form-group">
                    <label asp-for="Email" class="control-label"></label>
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>


                <div class="form-group">
                    <label asp-for="Year" class="control-label"></label>
                    <input asp-for="Year" class="form-control" />
                    <span asp-validation-for="Year" class="text-danger"></span>
                </div>


                <div class="form-group">
                    <label asp-for="Phone" class="control-label"></label>
                    <input asp-for="Phone" class="form-control" />
                    <span asp-validation-for="Phone" class="text-danger"></span>
                </div>


                @if (Model.Id is null)
                {
                    <div class="form-group">
                        <label asp-for="Password" class="control-label"></label>
                        <input asp-for="Password" class="form-control" />
                        <span asp-validation-for="Password" class="text-danger"></span>
                    </div>


                    <div class="form-group">
                        <label asp-for="PasswordConfirm" class="control-label"></label>
                        <input asp-for="PasswordConfirm" class="form-control" />
                        <span asp-validation-for="PasswordConfirm" class="text-danger"></span>
                    </div>
                }
                else
                {
                    <input asp-for="Password" type="hidden" value="Update12!s##8)" />
                    <input asp-for="PasswordConfirm" type="hidden" value="Update12!s##8)" />
                }


                <div class="mt-3"></div>
                <div class="form-group">
                    <input type="submit" value="Сохранить" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
</div>


@*Для валидации модели на клиенте*@
@await Html.PartialAsync("_ValidationScriptsPartial")

PizzaStar/Views/Panel/EditRole.cshtml
@using Microsoft.AspNetCore.Identity
@{
    Layout = "_PanelLayout.cshtml";
    ViewData["Title"] = "Изменение ролей пользователя";
}


<div class="row justify-content-center">
    <div class="col-sm-12">
        <div class="well mt-5">
            <h3>Изменение ролей пользователя</h3>
            <form asp-controller="Panel" asp-action="EditRole" method="post">
                <input type="hidden" name="userId" value="@Model.UserId" />
                <div class="form-group">
                    @foreach (IdentityRole role in Model.AllRoles)
                    {
                        <input type="checkbox" name="roles" value="@role.Name"
                        @(Model.UserRoles.Contains(role.Name) ? "checked=\"checked\"" : "") />
                        @role.Name <br />
                    }
                </div>
                <div class="form-group">
                    @Html.AntiForgeryToken()
                    <input type="submit" value="Сохранить" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
</div>


@*Для валидации модели на клиенте*@
@await Html.PartialAsync("_ValidationScriptsPartial")

PizzaStar/Views/Panel/Index.cshtml
@{
    Layout = "_PanelLayout.cshtml";
    ViewData["Title"] = "Главная";
}


<div class="breadcrumb-main">
    <div class="breadcrumb-container clearfix">
        <h1 class="page-title">Панель управления</h1>


        <ul class="breadcrumb">
            <li><a asp-action="Index" asp-controller="Panel">Главная</a></li>
        </ul>
    </div>
</div>


<div class="information-information">
    <h2 class="title">Добро пожаловать в панель управления сайтом!</h2>
    <p class="description">
        An natum nulla eruditi mei, te qui idque adipisci, nonumy graeci has ad. Cu diam dolor
        noluisse nec. Nam ex dicta graeco, audire nominati persequeris eu eos. Pri nibh dolor soleat
        cu, sanctus inermis instructior eum ei. Scripta ceteros sit ex. Et eum alia laudem delectus.
    </p>
</div>

PizzaStar/Views/Panel/RoleManager.cshtml
@model IEnumerable<Microsoft.AspNetCore.Identity.IdentityRole>

@{
    Layout = "_PanelLayout.cshtml";
    ViewData["Title"] = "Управление ролями";
}

<div class="breadcrumb-main">
    <div class="breadcrumb-container clearfix">
        <h1 class="page-title">Панель управления</h1>
        <ul class="breadcrumb">
            <li><a asp-action="Index" asp-controller="Panel">Главная</a></li>
            <li><a asp-action="Index" asp-controller="Role">Менеджер ролями</a></li>
        </ul>
    </div>
</div>

<form asp-controller="Role" asp-action="Create" method="post" class="mb-3">
    <div class="input-group">
        <input type="text" name="roleName" class="form-control" placeholder="Название роли" required />
        <button type="submit" class="btn btn-success">Добавить</button>
    </div>
</form>

<table class="table table-bordered">
    <thead>
    <tr>
        <th>Название</th>
        <th>Действия</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var role in Model)
    {
        <tr>
            <td>@role.Name</td>
            <td>
                <div class="d-flex">
                    <form asp-controller="Role" asp-action="Edit" method="post" class="d-flex flex-grow-1">
                        <input type="hidden" name="roleId" value="@role.Id" />
                        <input type="text" name="newRoleName" class="form-control flex-grow-1" placeholder="Новое имя" required />
                        <button type="submit" class="btn btn-warning me-2">Изменить</button>
                    </form>

                    <form asp-controller="Role" asp-action="Delete" method="post" class="d-inline">
                        <input type="hidden" name="roleId" value="@role.Id" />
                        <button type="submit" class="btn btn-danger" onclick="return confirm('Удалить роль?')">Удалить</button>
                    </form>
                </div>
            </td>

        </tr>
    }
    </tbody>
</table>

PizzaStar/Views/Panel/Statistics.cshtml
@{
    Layout = "_PanelLayout.cshtml";
    ViewData["Title"] = "Статистика";
}


<div class="breadcrumb-main">
    <div class="breadcrumb-container clearfix">
        <h1 class="page-title">Панель управления</h1>
        <ul class="breadcrumb">
            <li><a asp-action="Index" asp-controller="Panel">Главная</a></li>
            <li><a asp-action="Statistics" asp-controller="Panel">Статистика</a></li>
        </ul>
    </div>
</div>

PizzaStar/Views/Panel/_PanelLayout.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="blog-section">
    <div id="checkout-cart" class="container">
        <div class="row">


            <aside id="column-left" class="col-sm-3">
                <div class="category-content">
                    <div class="box-category">
                        <h3 class="toggled relative">Настройки</h3>
                        <ul class="list-unstyled parent" id="select-category">
                            <li>
                                <a asp-action="Index" asp-controller="Panel" class="list-group-item">Главная</a>
                            </li>
                            <li>
                                <a asp-action="Categories" asp-controller="Category" class="list-group-item">Категории</a>
                            </li>
                            <li>
                                <a asp-action="Dishes" asp-controller="Dish" class="list-group-item">Продукты</a>
                            </li>
                            @if (User.IsInRole("Admin"))
                            {
                                <li>
                                    <a asp-action="Users" asp-controller="Panel" class="list-group-item">Пользователи</a>
                                </li>
                                <li>
                                    <a asp-action="Statistics" asp-controller="Panel" class="list-group-item">Статистика</a>
                                </li>
                                <li>
                                    <a asp-action="Contact" asp-controller="Panel" class="list-group-item">Контактные данные</a>
                                </li>
                                <li>
                                    <a asp-action="Index" asp-controller="Role" class="list-group-item">Менеджер ролями</a>
                                </li>
                            }
                        </ul>
                    </div>
                </div>
            </aside>


            <div id="content" class="col-sm-9  all-blog">
                @*Основное содержимое страницы*@
                @RenderBody()
            </div>


        </div>
    </div>
</div>
<!-- Секция для подгрузки скриптов из других представлений -->
@await RenderSectionAsync("Scripts", required: false)