PizzaStar/Models/Category.cs
namespace PizzaStar.Models
{
    public class Category
    {
        public int? Id { get; set; }
        public string Name { get; set; }
        public string? Description { get; set; }
        public string? Image { get; set; }
        public DateTime DateOfPublication { get; set; }

    }
}

PizzaStar/ViewModels/CategoryViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace PizzaStar.ViewModels
{
    public class CategoryViewModel
    {
        [Key]
        public int? Id { get; set; }
        [Display(Name = "Название")]
        [Required(ErrorMessage = "Не указано название категории")]
        public string? Name { get; set; }
        [Display(Name = "Описание")]
        public string? Description { get; set; }
        [Display(Name = "Изображение")]
        public IFormFile? File { get; set; }
        public string? Image { get; set; }
        public DateTime DateOfPublication { get; set; }
    }
}

PizzaStar/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PizzaStar.Interfaces;
using PizzaStar.Models;
using PizzaStar.Models.Pages;
using PizzaStar.ViewModels;

namespace PizzaStar.Controllers
{
    [Authorize(Roles = "Admin,Editor")]
    public class CategoryController : Controller
    {
        private readonly ICategory _categories;
        private readonly IWebHostEnvironment _appEnvironment;
        public CategoryController(ICategory categories, IWebHostEnvironment appEnvironment)
        {
            _categories = categories;
            _appEnvironment = appEnvironment;
        }

        [Route("/panel/categories")]
        public IActionResult Categories(QueryOptions options)
        {
            return View(_categories.GetAllCategories(options));
        }

        [Route("/panel/create-category")]
        [HttpGet]
        public IActionResult CreateCategory()
        {
            return View();
        }


        [Route("/panel/create-category")]
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> CreateCategory(CategoryViewModel categoryViewModel)
        {
            if (ModelState.IsValid)
            {
                categoryViewModel.DateOfPublication = DateTime.Now;
                var currentCategory = new Category
                {
                    Name = categoryViewModel.Name!,
                    Description = categoryViewModel.Description,
                    DateOfPublication = categoryViewModel.DateOfPublication
                };
                if (categoryViewModel.File != null)
                {
                    string fileName = categoryViewModel.File.FileName;
                    if (fileName.Contains("\\"))
                    {
                        fileName = fileName.Substring(fileName.LastIndexOf('\\') + 1);
                    }
                    string filePath = "/categoryFiles/" + Guid.NewGuid().ToString() + fileName;
                    currentCategory.Image = filePath;


                    using (var fileStream = new FileStream(_appEnvironment.WebRootPath + filePath, FileMode.Create))
                    {
                        await categoryViewModel.File.CopyToAsync(fileStream);
                    }
                }
                await _categories.AddCategoryAsync(currentCategory);
                return RedirectToAction(nameof(Categories));
            }
            return View(categoryViewModel);
        }

        [Route("/panel/edit-category")]
        [HttpGet]
        public async Task<IActionResult> EditCategory(int categoryId)
        {
            var currentCategory = await _categories.GetCategoryAsync(categoryId);
            if (currentCategory != null)
            {
                CategoryViewModel categoryViewModel = new CategoryViewModel
                {
                    Id = currentCategory.Id,
                    Name = currentCategory.Name,
                    Image = currentCategory.Image,
                    Description = currentCategory.Description
                };
                return View(categoryViewModel);
            }
            return NotFound();
        }

        [Route("/panel/edit-category")]
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> EditCategory(CategoryViewModel categoryViewModel)
        {
            if (ModelState.IsValid)
            {
                var selectedCategory = await _categories.GetCategoryAsync(categoryViewModel.Id ?? 0);
                if (selectedCategory == null)
                {
                    return NotFound();
                }
                var currentCategory = new Category
                {
                    Id = categoryViewModel.Id,
                    Name = categoryViewModel.Name!,
                    Description = categoryViewModel.Description,
                    Image = selectedCategory.Image
                };
                if (categoryViewModel.File != null)
                {
                    if (selectedCategory.Image != null)
                    {
                        if (System.IO.File.Exists(_appEnvironment.WebRootPath + selectedCategory.Image))
                        {
                            System.IO.File.Delete(_appEnvironment.WebRootPath + selectedCategory.Image);
                        }
                    }
                    string fileName = categoryViewModel.File.FileName;
                    if (fileName.Contains("\\"))
                    {
                        fileName = fileName.Substring(fileName.LastIndexOf('\\') + 1);
                    }
                    string filePath = "/categoryFiles/" + Guid.NewGuid().ToString() + fileName;
                    currentCategory.Image = filePath;


                    using (var fileStream = new FileStream(_appEnvironment.WebRootPath + filePath, FileMode.Create))
                    {
                        await categoryViewModel.File.CopyToAsync(fileStream);
                    }
                }
                await _categories.EditCategoryAsync(currentCategory);
                return RedirectToAction(nameof(Categories));
            }
            return View(categoryViewModel);
        }

        [Route("/panel/delete-category")]
        [HttpDelete]
        public async Task<IActionResult> DeleteCategory(int categoryId)
        {
            var currentCategory = await _categories.GetCategoryAsync(categoryId);
            if (currentCategory != null)
            {
                if (currentCategory.Image != null)
                {
                    if (System.IO.File.Exists(_appEnvironment.WebRootPath + currentCategory.Image))
                    {
                        System.IO.File.Delete(_appEnvironment.WebRootPath + currentCategory.Image);
                    }
                }
                await _categories.DeleteCategoryAsync(currentCategory);
            }
            return Ok();
        }
    }
}

PizzaStar/Controllers/PanelController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PizzaStar.Data;
using PizzaStar.Models;
using PizzaStar.Models.Pages;
using PizzaStar.ViewModels;

namespace PizzaStar.Controllers
{
    [Authorize(Roles = "Admin,Editor")]
    public class PanelController : Controller
    {

        private readonly UserManager<User> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly ApplicationContext _context;
        public PanelController(UserManager<User> userManager, RoleManager<IdentityRole> roleManager, ApplicationContext context)
        {
            _userManager = userManager;
            _roleManager = roleManager;
            _context = context;
        }


        [Route("/panel")]
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }


        [Authorize(Roles = "Admin")]
        [Route("/panel/users")]
        [HttpGet]
        public IActionResult Users(QueryOptions options)
        {
            var pagedList = new PagedList<User>(_userManager.Users, options);
            return View(pagedList);
        }


        [Authorize(Roles = "Admin")]
        [Route("/panel/create-update-user")]
        [HttpGet]
        public async Task<IActionResult> CreateOrUpdateUser(string? userId)
        {
            if (userId is null)
            {
                return View(new CreateOrUpdateUserViewModel());
            }
            else
            {
                User user = await _userManager.FindByIdAsync(userId);
                if (user == null)
                {
                    return NotFound();
                }
                CreateOrUpdateUserViewModel model = new CreateOrUpdateUserViewModel
                {
                    Id = user.Id,
                    Email = user.Email,
                    Phone = user.PhoneNumber,
                    Year = user.Year,
                };
                return View(model);
            }
        }


        [Authorize(Roles = "Admin")]
        [Route("/panel/create-update-user")]
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> CreateOrUpdateUser(CreateOrUpdateUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (model.Id is null)
                {
                    var userCheck = await _userManager.FindByEmailAsync(model.Email);
                    if (userCheck != null)
                    {
                        ModelState.AddModelError("Email", "Такой емейл адрес уже занят.");
                        return View(model);
                    }
                    User user = new User { Email = model.Email, UserName = model.Email, PhoneNumber = model.Phone, Year = model.Year };
                    var result = await _userManager.CreateAsync(user, model.Password);
                    if (result.Succeeded)
                    {
                        result = await _userManager.AddToRoleAsync(user, "Client");
                        return RedirectToAction(nameof(Users));
                    }
                    else
                    {
                        foreach (var error in result.Errors)
                        {
                            ModelState.AddModelError(string.Empty, error.Description);
                        }
                    }
                }
                else
                {
                    User user = await _userManager.FindByIdAsync(model.Id);
                    if (user != null)
                    {
                        if (!user.Email.Equals(model.Email))
                        {
                            var userCheck = await _userManager.FindByEmailAsync(model.Email);
                            if (userCheck != null)
                            {
                                ModelState.AddModelError("Email", "Такой емейл адрес уже занят.");
                                return View(model);
                            }
                        }
                        user.Email = model.Email;
                        user.UserName = model.Email;
                        user.Year = model.Year;
                        user.PhoneNumber = model.Phone;
                        var result = await _userManager.UpdateAsync(user);
                        if (result.Succeeded)
                        {
                            return RedirectToAction(nameof(Users));
                        }
                        else
                        {
                            foreach (var error in result.Errors)
                            {
                                ModelState.AddModelError(string.Empty, error.Description);
                            }
                        }
                    }
                }
            }
            return View(model);
        }

        [Authorize(Roles = "Admin")]
        [Route("/panel/delete-user")]
        [HttpDelete]
        public async Task<ActionResult> DeleteUser(string userId)
        {
            User user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                IdentityResult result = await _userManager.DeleteAsync(user);
            }
            return Ok();
        }


        [Authorize(Roles = "Admin")]
        [Route("/panel/edit-role")]
        [HttpGet]
        public async Task<IActionResult> EditRole(string userId)
        {
            // получаем пользователя
            User user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                // получаем список ролей пользователя
                var userRoles = await _userManager.GetRolesAsync(user);
                var allRoles = _roleManager.Roles.ToList();
                ChangeRoleViewModel model = new ChangeRoleViewModel
                {
                    UserId = user.Id,
                    UserEmail = user.Email,
                    UserRoles = userRoles,
                    AllRoles = allRoles
                };
                return View(model);
            }
            return NotFound();
        }


        [Authorize(Roles = "Admin")]
        [Route("/panel/edit-role")]
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> EditRole(string userId, List<string> roles)
        {
            // получаем пользователя
            User user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                // получем список ролей пользователя
                var userRoles = await _userManager.GetRolesAsync(user);


                // получаем список ролей, которые были добавлены
                var addedRoles = roles.Except(userRoles);
                // получаем роли, которые были удалены
                var removedRoles = userRoles.Except(roles);


                await _userManager.AddToRolesAsync(user, addedRoles);
                await _userManager.RemoveFromRolesAsync(user, removedRoles);


                return RedirectToAction(nameof(Users));
            }
            return NotFound();
        }

        [Authorize(Roles = "Admin")]
        [Route("/panel/statistics")]
        [HttpGet]
        public IActionResult Statistics()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        [Route("/panel/set-contact")] 
        [HttpGet]
        public IActionResult Contact(QueryOptions options)
        {
            var pagedList = new PagedList<Contact>(_context.Contacts, options);
            return View(pagedList);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> CreateContact(string email)
        {
            if (ModelState.IsValid)
            {
                await _context.Contacts.AddAsync(new Contact{Email = email});
                await _context.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Contact));
        }

        [Authorize(Roles = "Admin")]
        [HttpDelete]
        [Route("/panel/delete-contact")]
        public IActionResult DeleteContact(string id)
        {
            if (!int.TryParse(id, out int contactId))
            {
                return BadRequest("Некорректный ID");
            }

            var email = _context.Contacts.Find(contactId);
            if (email == null)
            {
                return NotFound("Email не найден");
            }

            _context.Contacts.Remove(email);
            _context.SaveChanges();

            return Ok(new { message = "Email удалён успешно" });
        }
    }
}

PizzaStar/Views/Category/Categories.cshtml
@{
    Layout = "~/Views/Panel/_PanelLayout.cshtml";
    ViewData["Title"] = "Категории";
}
@model IEnumerable<Category>


<div class="breadcrumb-main">
    <div class="breadcrumb-container clearfix">
        <h1 class="page-title">Панель управления</h1>
        <ul class="breadcrumb">
            <li><a asp-action="Index" asp-controller="Panel">Главная</a></li>
            <li><a asp-action="Categories" asp-controller="Category">Категории</a></li>
        </ul>
    </div>
</div>


<div class="row g-4 py-5 row-cols-1">


    <a asp-action="CreateCategory" asp-controller="Category" class="btn btn-primary">Добавить новую категорию</a>


    <div class="input-group themability-search">
        @{
            ViewBag.searches = new string[] { "Name", "Description" };
        }
        @await Html.PartialAsync("_SearchOptions", Model)
    </div>


    <div class="p-5 mb-4 bg-light rounded-3 ovx table-responsive">
        <table class="table">
            <tr><th>Название</th><th>Описание</th><th>Дата публикации</th><th></th><th></th></tr>
            @foreach (var category in Model)
            {
                @*Обязательно прописываем данный атрибут
            С помощью него мы удалим данную строку,
            используя JavaScript*@
                <tr data-rowid="@category.Id">
                    <td>@category.Name</td>
                    <td>@category.Description</td>
                    <td>@category.DateOfPublication.ToShortDateString()</td>
                    <td><a class="btn btn-sm btn-primary" asp-action="EditCategory" asp-controller="Category" asp-route-categoryId="@category.Id">Изменить</a></td>
                    <td>
                        @*Обязательно прописываем onClick и метод, который будет обрабатывать клик*@
                        <button onclick="deleteCategory('@category.Id')" class="btn btn-sm btn-danger">Удалить</button>
                    </td>
                </tr>
            }
        </table>


        <div class="text-center">
            @await Html.PartialAsync("_Pages", Model)
        </div>


        @await Html.PartialAsync("_Modal", "Удалить выбранную категорию?")


        @section Scripts {
            <script>
                async function deleteCategory(categoryId) {


                    const btnYes = document.getElementById('btn-Yes');
                    const btnNo = document.getElementById('btn-No');


                    console.log(categoryId);
                    $('#confirmModal').modal('show');


                    //Если нажали да, удаляем
                    btnYes.onclick = () => {
                        const deleteItem = fetch(`/panel/delete-category/?categoryId=${categoryId}`, { method: 'DELETE' })
                            .then(response => {
                                if (!response.ok) {
                                    throw new Error('Network response was not ok');
                                }
                                //Удаляем строку
                                document.querySelector("tr[data-rowid='" + categoryId + "']").remove();
                                //Закрываем модальное окно
                                $('#confirmModal').modal('hide');
                            })
                            .catch(error => {
                                console.error('There was a problem with the fetch operation:', error);
                                // Обработка ошибки удаления
                            });
                    }
                    //Если нажали нет, скрываем
                    btnNo.onclick = () => {
                        $('#confirmModal').modal('hide');
                    }
                }
            </script>
        }
    </div>
</div>

PizzaStar/Views/Category/CreateCategory.cshtml
@{
    Layout = "~/Views/Panel/_PanelLayout.cshtml";
    ViewData["Title"] = "Добавление категории";
}
@model CategoryViewModel


<div class="row justify-content-center">
    <div class="col-sm-12">
        <div class="well mt-5">
            <h3>Добавление категории</h3>
            <form asp-action="CreateCategory" asp-controller="Category" method="post" enctype="multipart/form-data">
                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Name" class="control-label">Название</label>
                    <input type="text" asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description" class="control-label">Описание</label>
                    <textarea asp-for="Description" class="form-control"></textarea>
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="File" class="control-label">Изображение</label>
                    <input type="file" class="form-control" asp-for="File" accept="image/*" />
                </div>
                <br />
                <div class="form-group">
                    @Html.AntiForgeryToken()
                    <input type="submit" value="Добавить" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
</div>


@*Для валидации модели на клиенте*@
@await Html.PartialAsync("_ValidationScriptsPartial")

PizzaStar/Views/Category/EditCategory.cshtml
@{
    Layout = "~/Views/Panel/_PanelLayout.cshtml";
    ViewData["Title"] = "Редактирование категории";
}
@model CategoryViewModel


<div class="row justify-content-center">
    <div class="col-sm-12">
        <div class="well mt-5">
            <h3>Редактирование категории</h3>
            <form asp-action="EditCategory" asp-controller="Category" method="post" enctype="multipart/form-data">
                <div asp-validation-summary="All" class="text-danger"></div>


                <input type="hidden" asp-for="Id" />


                <div class="form-group">
                    <label asp-for="Name" class="control-label">Название</label>
                    <input type="text" asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description" class="control-label">Описание</label>
                    <textarea asp-for="Description" class="form-control"></textarea>
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="File" class="control-label">Изображение</label>
                    @if (Model.Image != null)
                    {
                        <div class="category-img col-sm-3">
                            <img src="@Model.Image" alt="@Model.Name" class="img-responsive">
                        </div>
                    }
                    <input type="file" class="form-control" asp-for="File" accept="image/*" />
                </div>
                <br />
                <div class="form-group">
                    @Html.AntiForgeryToken()
                    <input type="submit" value="Сохранить" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
</div>


@*Для валидации модели на клиенте*@
@await Html.PartialAsync("_ValidationScriptsPartial")